import dotenv from 'dotenv';
import path from 'path';

const envFile = process.env.NODE_ENV === 'production' ? '.env.production' : '.env';
dotenv.config({ path: path.resolve(process.cwd(), envFile) });

export const env: {
    NODE_ENV: string,
    PORT: number,
    DATABASE_URL: string,
    JWT_ACCESS_SECRET: string,
    JWT_REFRESH_SECRET: string,
    JWT_ACCESS_EXPIRY: string,
    JWT_REFRESH_EXPIRY: string,
    BCRYPT_SALT_ROUNDS: number,
    ACCESS_TOKEN_MAX_AGE: number,
    REFRESH_TOKEN_MAX_AGE: number,
    SITE_URL: string,
    URL_FILE_SIZE: string,
    MULTER_FILE_SIZE: number,
    FIREBASE_PROJECT_ID: string,
    FIREBASE_CLIENT_EMAIL: string,
    FIREBASE_PRIVATE_KEY: string,
    STRIPE_SECRET_KEY: string,
    STRIPE_WEBHOOK_SECRET: string,
    CLOUDINARY_CLOUD_NAME: string,
    CLOUDINARY_API_KEY: string,
    CLOUDINARY_API_SECRET: string,
    DEFAULT_PREMIUM_FEE: number,
    SMTP_HOST: string,
    SMTP_PORT: number,
    SMTP_SECURE: boolean,
    SMTP_USER: string,
    SMTP_PASS: string,
    EMAIL_FROM: string,
} = {
    NODE_ENV: process.env.NODE_ENV || 'development',
    PORT: parseInt(process.env.PORT || '3000', 10),
    DATABASE_URL: process.env.DATABASE_URL || '',
    JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET || 'dev_jwt_access_secret_super_secure_key_123',
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'dev_jwt_refresh_secret_super_secure_key_456',
    JWT_ACCESS_EXPIRY: process.env.JWT_ACCESS_EXPIRY || '15m',
    JWT_REFRESH_EXPIRY: process.env.JWT_REFRESH_EXPIRY || '7d',
    BCRYPT_SALT_ROUNDS: parseInt(process.env.BCRYPT_SALT_ROUNDS || '10', 10),
    ACCESS_TOKEN_MAX_AGE: 900000,
    REFRESH_TOKEN_MAX_AGE: 604800000,
    SITE_URL: process.env.SITE_URL || "http://localhost:5173",
    URL_FILE_SIZE: process.env.URL_FILE_SIZE || "25mb",
    MULTER_FILE_SIZE: parseInt(process.env.MULTER_FILE_SIZE || '45', 10),
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || '',
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL || '',
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY || '',
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || 'sk_test_mock_stripe_key_placeholder',
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || '',
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME || '',
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY || '',
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET || '',
    DEFAULT_PREMIUM_FEE: parseFloat(process.env.DEFAULT_PREMIUM_FEE || '25.00'),
    SMTP_HOST: process.env.SMTP_HOST || 'smtp.gmail.com',
    SMTP_PORT: parseInt(process.env.SMTP_PORT || '465', 10),
    SMTP_SECURE: process.env.SMTP_SECURE !== 'false',
    SMTP_USER: process.env.SMTP_USER || '',
    SMTP_PASS: process.env.SMTP_PASS || '',
    EMAIL_FROM: process.env.EMAIL_FROM || 'CityCare Pro <noreply@citycare.gov>',
};